language: python
python:
  - 2.7
  - 3.3
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source ./pydfs_lineup_optimizer -m unittest discover -s tests/
after_success:
  coveralls